### PR TITLE
make an exception for --with-libbfd for Score-P versions older than v1.4

### PR DESCRIPTION
**Pull request by boegel**
fix for https://github.com/hpcugent/easybuild-easyblocks/pull/889

### CODE REVIEW

**Comment by geimer** [comment]
@boegel: Could you please provide me with the relevant parts of the build logs for the older Score-P versions?  I just manually (i.e., w/o EB) checked older versions back to 1.2.1 (the oldest one for which we have an easyconfig file) and it worked as documented for me...  I'm a little bit puzzled now...

**Comment by boegel** [comment]
@geimer: OK, on it, I'll provide them ASAP

**Comment by geimer** [comment]
@boegel: In fact, you already did, see https://github.com/hpcugent/easybuild-easyblocks/pull/889/files/c409e71bcea682e3a74153dc9da9a254840870d2#r63216927 (and I forgot).  However, it is unclear to which version it applies.

**Comment by boegel** [comment]
@geimer: full logs for `Score-P-1.2.1-gompi-1.4.12-no-OFED.eb` @ https://gist.github.com/boegel/d2b0129481846a5a80892167b16b9e91

**Comment by geimer** [comment]
@boegel: OK, tracked it down...
- The `configure` option works as documented.
- binutils 2.25 installs all libraries in `<prefix>/lib`, while binutils 2.22 used by the older configurations installs some in `<prefix>/lib` (e.g., libbfd) and some in `<prefix>/lib64` (libiberty).
- On x86_64, Score-P's configure uses `<prefix>/lib64` if it exists, `<prefix>/lib` otherwise.  Thus, it can't find `libbfd.a` when binutils 2.22 is used.  I would agree that this behavior is debatable, but that's the way it is right now.
- When an invalid prefix (such as `<prefix>/lib`) is passed in via `--with-libbfd=`, `configure` detects that the extended path (i.e., `<prefix>/lib/lib`) doesn't exist and skips the link check.  Thus, although your PR makes the `configure` run through, compiler instrumentation will still be disabled.

Unfortunately, it seems that we need both `libbfd.a` and `libiberty.a`, thus using `--with-libbfd-include=...` and `--with-libbfd-lib=...` is not really an option, as both only support a single path.  I'm not yet sure how best to proceed...

**Comment by boegel** [comment]
OK, so building Score-P with compiler instrumentation on top of binutils 2.22 was never supported?

For now, I'd somehow restore building the older Score-P versions, if even it is without compiler instrumentation?
Maybe we can detect older versions of binutils, and skip specifying `--with-libbfd` in that case?

**Comment by geimer** [comment]
It's getting worse... If I compile binutils 2.22 outside of EB with my system's GCC (4.9.2), everything ends up in `lib`.  When using GCC 4.7.3 from `gompi/1.4.12-no-OFED`, I get the split layout. No clue what's going on here...

I also tried GCC 4.9.3 from EB, but it can't compile the binutils code.

**Comment by boegel** [comment]
@geimer: well, we can make the Score-P easyblock check where `libbfd.a` and `libiberty.a` are, and skip on `--with-libbfd` if they're in separate `lib`/`lib64` directories?

**Comment by geimer** [comment]
@boegel: Thinking about it again, `libiberty.a` is also provided by GCC/GCCcore.  Thus, the solution now pushed to https://github.com/hpcugent/easybuild-easyblocks/pull/889 should be safe (and works for me).

**Comment by boegel** [comment]
fix in https://github.com/hpcugent/easybuild-easyblocks/pull/889 verified, so closing this

**Pull request closed without merging**
